name: Update CDN

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Update CDN
      run: |
        # Use cURL to upload the content of style.css to the CDN URL
        curl -X PUT -d @style.css https://cdn.jsdelivr.net/gh/arismoraitis/ogibiz@master/style.css
